### ISSUE TITLE
[BUG] KeyError: 'data' (com.plexapp.agents.kinopoisk2.log)

### ISSUE THREAD

**Issue by kidiboy** [amirotin/Kinopoisk.bundle#34]
**Описание ошибки**
Не подгружаются данные с кинопоиск. В логах присутствует ошибка:
```
2020-06-12 22:57:26,998 (7fc0f0ff6700) :  ERROR (utils:232) - 'data'
Traceback (most recent call last):
  File "/volume3/Plex/Library/Application Support/Plex Media Server/Plug-ins/Kinopoisk.bundle/Contents/Libraries/Shared/kinoplex/utils.py", line 228, in update_event
    self.fire('update', metadict, media, lang, force, periodic)
  File "/volume3/Plex/Library/Application Support/Plex Media Server/Plug-ins/Kinopoisk.bundle/Contents/Libraries/Shared/kinoplex/agent.py", line 15, in fire
    [getattr(s, event)(*args, **kwargs) for s in self.sources]
  File "/volume3/Plex/Library/Application Support/Plex Media Server/Plug-ins/Kinopoisk.bundle/Contents/Libraries/Shared/kinoplex/sources/tvdb.py", line 63, in update
    episodes_data.extend(episode_data_page['data'])
KeyError: 'data'
```

**Шаги для вопроизведения ошибки**
1. Скачать полный сезон [сериала](https://www.lostfilm.tv/series/The_Mandalorian/seasons/) (качество 1080p)
2. В библиотеке Plex он появится :
![image](https://user-images.githubusercontent.com/55297357/84542457-2590ae00-ad02-11ea-83f1-9ee5341d9410.png)
3. Постер, описание и пр. не подгрузились
4. Пункт "Обновить метеданные" не помогает.

**Ожидание**
Четкое и краткое описание того, что вы ожидали.

**Скриншоты**
![image](https://user-images.githubusercontent.com/55297357/84542704-aea7e500-ad02-11ea-90d8-bde72ec1e9c0.png)
![image](https://user-images.githubusercontent.com/55297357/84542748-c2534b80-ad02-11ea-9357-f21e5e362a8f.png)

**Характеристики сервера PLEX и версия агента КиноПоиск:**
 - OS: Synology DSM
 - Браузер: chrome
 - Версия PLEX: Версия 1.19.4.2935
 - Версия агента кинопоиск: #v2.0.10

**Дополнительная информация**
Логи:
[com.plexapp.agents.kinopoisk2.1.log](https://github.com/amirotin/Kinopoisk.bundle/files/4773094/com.plexapp.agents.kinopoisk2.1.log)
[com.plexapp.agents.kinopoisk2.log](https://github.com/amirotin/Kinopoisk.bundle/files/4773088/com.plexapp.agents.kinopoisk2.log)

**Comment by kidiboy** [comment]
Возможно, это связано с изменением верстки кинопоиска у части фильмов?
Не работает - https://www.kinopoisk.ru/series/1118138/
Работает - https://www.kinopoisk.ru/film/1112539/

Помимо верстки на двух разных версиях верстки и разные пути к постерам, о чем упоминалось тут: https://github.com/amirotin/Kinopoisk.bundle/issues/33#issuecomment-643299345

@ziemenz @amirotin, что думаете?
